# Generated by Django 5.2.8 on 2025-11-13 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(null=True, verbose_name='Birth date')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='სათაური')),
                ('text', models.TextField(verbose_name='ტექსტი')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიურია')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='შექმნის თარიღი')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='განახლების თარიღი')),
                ('website', models.URLField(null=True, verbose_name='ვებ მისამართი')),
                ('document', models.FileField(null=True, upload_to='blog_post_documents/')),
                ('category', models.IntegerField(choices=[(1, 'Technology'), (2, 'Lifestyle'), (3, 'Sports'), (4, 'News'), (5, 'Other')], null=True, verbose_name='Category')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('authors', models.ManyToManyField(related_name='blog_posts', to='blog.author', verbose_name='Authors')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['title', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostAuthorThroughTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author', verbose_name='Authors')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogpost', verbose_name='BlogPost')),
            ],
            options={
                'verbose_name': 'Blog Post author through table',
                'verbose_name_plural': 'Blog Posts',
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='authors_2',
            field=models.ManyToManyField(related_name='blog_posts_2', through='blog.BlogPostAuthorThroughTable', to='blog.author', verbose_name='Authors 2'),
        ),
        migrations.CreateModel(
            name='BlogPostCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_post_covers/', verbose_name='Image')),
                ('blog_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='blog.blogpost', verbose_name='Blog Post')),
            ],
            options={
                'verbose_name': 'Blog Post Cover',
                'verbose_name_plural': 'Blog Post Covers',
            },
        ),
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog_post_images/', verbose_name='Image')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blogpost', verbose_name='Blog Post')),
            ],
            options={
                'verbose_name': 'Blog Post Image',
                'verbose_name_plural': 'Blog Post Images',
            },
        ),
        migrations.AlterUniqueTogether(
            name='blogpost',
            unique_together={('title', 'text')},
        ),
    ]
